name: appandup_lint
description: App and Up SRL Lint preferences for Dart and Flutter applications.
version: 0.0.5
homepage: https://github.com/App-and-Up/appandup_lint

environment:
  sdk: ">=2.12.0 <3.0.0"

